name: mkdocs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
    steps:
    - name: Build
    run: mkdocs build
    - name: Deploy 🚀
    run: python3 -m mkdocs gh-deploy --force
